### ISSUE TITLE
Hunger: Parse PDF and display on site 

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#1]
Anyone might try to parse the PDF into HTML so we can display it direct in the browser. This would prevent (mobile) users do download the pdf mutilple times.

If we got it, we can add the mensa plan aswell ( #2 )

**Comment by mammuth** [comment]
Can be done with: http://www.pdfparser.org/

**Comment by prexlebre** [comment]
I might try to solve this using https://github.com/Yuras/pdf-toolbox sometime in the future...

**Comment by mammuth** [comment]
More easy (even if not sure it's gonna always gonna work in the future):
Parse the html from this site: http://wwwrbgalt.in.tum.de/idienste/FMI_Bistro/aktuell.html
