### ISSUE TITLE
The "Aktions Menü" is missing on hunger.tum.sexy

### ISSUE THREAD

**Issue by alexandervanrenen** [mammuth/TUM.sexy#103]
The FMI Bistro offers a special menu that changes every week. It would be nice to include this on [hunger.tum.sexy](hunger.tum.sexy).

The menu can be found [here](http://www.wilhelm-gastronomie.de/wp-content/uploads/2018/02/Garching_Speiseplan_KW_09_2018.pdf).

**Comment by mammuth** [comment]
Thanks @alexandervanrenen, there is an related issue in the upstream eat api: https://github.com/srehwald/eat-api/issues/14

**Comment by kordianbruck** [comment]
PR is up: https://github.com/srehwald/eat-api/pull/22

**Comment by kordianbruck** [comment]
:white_check_mark: deployment
:white_check_mark: cache cleared
:white_check_mark: verified
