### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by kordianbruck** [mammuth/TUM.sexy#107]
Once we move to docker, we can work on automating deployment once again.

**Comment by jpbernius** [comment]
Can you share more insights on the server setup you imagine?
There are a couple of points to address:

Should the server itself run a web server, or should it run in docker?
Do we want to use nginx or apache?
Do we want to run php via cgi or fpm?

Should we publish du Docker Hub?
Do we want to use Docker Compose or something like that?

**Comment by kordianbruck** [comment]
The server itself will handle SSL certificates and proxy the requests to the docker image. Either via Caddy or an Docker Swarm Ingress - not sure, what the best solution here is.

You will need a FPM Server inside the image, but can probably skip using a full ubuntu image with its own nginx. There are some tricks we need to think about, especially the apacht `.htaccess` rewriting needs to be handled accordingly.

We can publish to docker hub, but I'm looking to setting up my very own registry. I also have a jenkins server we can run this build on, if travis CI is not sufficient.

Docker compose is certainly an option we can consider, but as we don't have multiple images or databases in anywhere, it should be sufficient to have a single `Dockerfile`

**Comment by jpbernius** [comment]
I have used [Traefik](https://traefik.io) before for Proxying and SSL Termination. Ok, can start with a `Dockerfile`.
Travis can handle docker with non-container based infrastructure. Otherwise we could also try out [CircleCi](circleci.com).

**Comment by kordianbruck** [comment]
docker swarm has its own mesh routing: (https://docs.docker.com/engine/swarm/ingress/)
Any advantage in using traefik? I'm up to try out new things.

**Comment by kordianbruck** [comment]
Ok - Treafik does look really cool. I'm sold to set this up.

**Comment by jpbernius** [comment]
See WIP in #108
Is the server running TUM.sexy exclusively? That way we can set everything up in one `docker-compose.yml` file.
Should travis deploy stuff to the server directly?

**Comment by kordianbruck** [comment]
No, there are several services run on that swarm network. Not sure, what are the alternatives to having travis deploy directly? 
Isn't it usually done via a registry?

**Comment by jpbernius** [comment]
I know you have used some Webhook for deployment before. Maybe it is easier to have travis SSH into the box and execute a script (e.g. pull from whatever registry and restart)

**Comment by kordianbruck** [comment]
@jpbernius I'd rather do a jenkins build, where the delivery can be easier configured in a custom environment. I'm not a fan of having some service log on my servers and run commands. Unless you have a better idea? 
(Polling in a cronjob if there is a new image not being an option :grin:)

**Comment by kordianbruck** [comment]
@mathiasquintero any ideas on how to do the deployment? This might be relevant for you as well :stuck_out_tongue_closed_eyes:

**Comment by jpbernius** [comment]
Wouldn't Jenkins do the same thing (just you hosting it yourself)
Maybe doing something like [this](https://www.thomas-krenn.com/de/wiki/Ausführbare_SSH-Kommandos_per_authorized_keys_einschränken)?

If the server where to run it's own docker registry, maybe you can hook into its lifecycle somehow?

**Comment by mathiasquintero** [comment]
I suggest going simple. Travis CI on git tag. And running ssh to the correct server and wether or not we use docker compose or docker run I don't mind.

We could also let travis it self build the image and upload it to docker hub and just trigger a download and run in the server

**Comment by mathiasquintero** [comment]
We do something like this on a another project: https://github.com/BreakOutEvent/breakout-backend/blob/develop/deploy.sh

**Comment by kordianbruck** [comment]
Lol, no. Guys, having random deployment scripts that no one has any clear idea how they work/interact with each other is not the way to go. In a years time the script will break, because the zip file you download contains expired credentials or something.

How about using something like this? 
https://github.com/v2tec/watchtower/blob/master/README.md

**Comment by kordianbruck** [comment]
Especially once we split up the campus app backend into 5-10 micro services, I don't want to maintain random scripts everywhere. Plus TravisCI still can see any credentials in that zip you are sending. Like WTF.

**Comment by kordianbruck** [comment]
@mathiasquintero yea, no worries, I just dislike the idea of having random scripts doing stuff, no one is aware of. So I think watchtower will be the way to go, as it is super simple to setup.

**Comment by jpbernius** [comment]
Ok, I do not care to much about that tbh, you manage your sever the way you like. Lets decide on how we manage the Docker Image/Container setup over in #108.

**Comment by kordianbruck** [comment]
Just waiting, to see if my ispconfig administration will implement wildcards with the DNS challenge soon, or if I have to manually configure certbot. We could then move over to the docker deployment with SSL in one go.

**Comment by jpbernius** [comment]
Traefik can also take care of LetsEncrypt if that is a path you would like to follow.

**Comment by kordianbruck** [comment]
It does not yet support acmev2 nor wildcard certs. But yes, I will look into it.

**Comment by jpbernius** [comment]
@kordianbruck Deployment to Docker Hub is up and running.

**Comment by jpbernius** [comment]
I just stumbled across this, maybe relevant? [Neilpang/acme.sh](https://github.com/Neilpang/acme.sh)

**Comment by kordianbruck** [comment]
@mammuth whats the dockerhub link again? I can't find it somehow... :man_facepalming:

**Comment by kordianbruck** [comment]
Ok, just to let you guys know what the current state is: I have everything working, Kubernetes, Traefik, the docker image, wildcard cert. Currently Traefik is having problems correctly reading the cert from the secure storage - I might have to move over to nginx after all, as this is really beta right now. 

I'll have to think about this some more. For the time being I've updated the current deployment without docker.

**Comment by mammuth** [comment]
@kordianbruck https://hub.docker.com/r/mammuth/tum.sexy/

**Comment by kordianbruck** [comment]
I've switched over to a nginx Ingress Controller for Kubernetes and am pulling a LE SAN certificate now with acme.sh - seems to work well. 

I've redirected the DNS entries to point to the new installation.
