### ISSUE TITLE
Calendar proxy broken

### ISSUE THREAD

**Issue by git-commit** [mammuth/TUM.sexy#11]
http://tum.sexy/calendar/ redirects to the outdated link https://calproxy.kbruck.name/

The calendar proxy's url is now http://cal.bruck.me/

**Comment by mammuth** [comment]
@kordianbruck might you update it according to your current domain? Or better let's add an ssl certificate for tum.sexy and use that domain?

**Comment by kordianbruck** [comment]
I really don't care if it is under the tum.sexy or my domain. We can do both or just fix the forwarding...

**Comment by kordianbruck** [comment]
Fixed the URL. Will keep it under my domain for time being, as we don't have a SSL Wildcard certificate for tum.sexy

**Comment by lukf** [comment]
Let’s use Let’s Encrypt when they start offering free wildcart certs in Q1 2018! 🙂

**Comment by kordianbruck** [comment]
For sure! Feel free to open a New issue
