### ISSUE TITLE
PHP Error on shuttle.tum.sexy

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#127]
`Fatal error: Uncaught Error: Call to undefined function apcu_exists() in /var/www/html/shuttle/index.php:6 Stack trace: #0 {main} thrown in /var/www/html/shuttle/index.php on line 6`

**Comment by kordianbruck** [comment]
php-apcu dependancy is missing in the docker image. We would need to switch over to one of the stretch or alpine images and install it manually

**Comment by mammuth** [comment]
Related #107
