### ISSUE TITLE
Sort electives by name on frontpage

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#128]
Currently electives are displayed in the way they've been added to the array. It's a bit cleaner to have it sorted by the names of the lectures.

**Comment by kordianbruck** [comment]
We could simply reorder the entries in the array and add a comment for this invariant. Is it worth sorting this in the code?

**Comment by mammuth** [comment]
Sure, why not.

**Comment by mammuth** [comment]
Just wanted to come up with a "good first issue" :grin:
