### ISSUE TITLE
wal.tum.sexy

### ISSUE THREAD

**Issue by zepatrik** [mammuth/TUM.sexy#142]
What about adding [wal.tum.sexy](wal.tum.sexy), a page just showing a [whale](https://unsplash.com/photos/Cu6I_d8gw5A) inside a link to [wahl.tum.sexy](wahl.tum.sexy)? Would that be merged?

**Comment by kordianbruck** [comment]
Sure, we just don't have any way of showing HTML content before a redirect.

**Comment by kordianbruck** [comment]
The elections are over - we can revisit this next year.
