### ISSUE TITLE
The last entry of the FMI Bistro Menu doesn't get displayed correctly

### ISSUE THREAD

**Issue by timozandonella** [mammuth/TUM.sexy#156]
On _hunger_ the content of the first bullet point on the FMI Bistro side isn't correct right now. It should be displaying the last cell of the "Speiseplan"-PDF, instead it displays the content of all last cells of the whole week rowwise.

![2](https://user-images.githubusercontent.com/17074517/43416401-6ed144ce-9438-11e8-8719-6f785153af0f.png)

This is how this gets displayed on _hunger_:

![2018-07-30 20_36_54-window](https://user-images.githubusercontent.com/17074517/43416402-6eec9b7a-9438-11e8-855b-71f87ee998dd.png)

**Comment by jpbernius** [comment]
I guess this is related to srehwald/eat-api#36

**Comment by jpbernius** [comment]
Closed by srehwald/eat-api#36

**Comment by kordianbruck** [comment]
@jpbernius so we can close here as well right?
