### ISSUE TITLE
Domain sometimes resolves to different IP

### ISSUE THREAD

**Issue by DerGenaue** [mammuth/TUM.sexy#17]
I always get 302 moved temporarily to "http://tum.sexy/redirects.php"
which doesn't exist (for pages like propra.tum.sexy, wait, are you guys just working in this?).

Maybe forgot to update .htaccess or something?

Occurs for all non-existing subdomains

**Comment by DerGenaue** [comment]
How should I analyse the bug when you fix it?

**Comment by DerGenaue** [comment]
Wait... only for names longer than 4 chars?

(asd.tum.sexy vs. asdf.tum.sexy)

**Comment by mammuth** [comment]
This seems to appear from time to time, I have no clue how to reproduce it.

@kordianbruck there you go ;-)

**Comment by DerGenaue** [comment]
Wait... what?!
Why is the IP different ?!

![not working](https://cloud.githubusercontent.com/assets/7558512/10771090/2f173126-7cef-11e5-83f9-d589e003b919.PNG)

vs.

![working](https://cloud.githubusercontent.com/assets/7558512/10771107/4a236df4-7cef-11e5-8d26-15b9394e24fb.PNG)

**Comment by DerGenaue** [comment]
That other IP belongs to namecheap.com

**Comment by DerGenaue** [comment]
aaaaaaand it has nothing to do with subdomain name lengths,
now everything works for me and nothing for a friend of mine...
seems to be a DNS problem

**Comment by kordianbruck** [comment]
Yes this is defiantly a DNS issue - I guess there is some misconfiguration. 

@mammuth add me as an admin please on namecheap

**Comment by DerGenaue** [comment]
My friend tried to ping anal.tum.sexy from two machines from the same network...

Yep, you guessed it... two different IPs

**Comment by kordianbruck** [comment]
I tried to lookup from all NS Servers using this tool: https://www.ultratools.com/tools/dnsLookupResult

IPs look good on all of them. The Mail server looks buggy as hell.

**Comment by mammuth** [comment]
Waiting for #21

**Comment by kordianbruck** [comment]
Still an issue? I think there simply was a DNS Cache somewhere.

**Comment by mammuth** [comment]
I didn't experience it anymore, so let's close it for now.
