### ISSUE TITLE
Policy for adding entries to the "Projects/Links" section?

### ISSUE THREAD

**Issue by lukaskollmer** [mammuth/TUM.sexy#182]
I made [this](https://github.com/lukaskollmer/tum-lecture-download) a while ago and while it currently doesn't have a crazy amount of users, i guess it might be useful to some people.

Would that fall within the scope of the projects section?
If yes, which file should i modify to add an entry to the list?

**Comment by mammuth** [comment]
Sure, go for it. I think the projects section is completely defined in the corresponding template.

**Comment by mammuth** [comment]
Closed by #183
