### ISSUE TITLE
coffee.tum.sexy

### ISSUE THREAD

**Issue by zepatrik** [mammuth/TUM.sexy#190]
I am thinking of adding a list of all points to get coffee like `hunger`. I would collect all data (coffee variants & prices) next week. What about a drop down to select your preferred coffee and the ability to sort the results by price/distance from location?

**Comment by kordianbruck** [comment]
@zepatrik great idea! It would be just really good, if its extensible. So maybe just use json or even better an array, just like the routes.

**Comment by zepatrik** [comment]
Right, maybe it would be best to write it as a JS object literal in a separate file.
As I probably need some dependency at some point, what about adding npm and a webpack/browserify build of the JS?

**Comment by kordianbruck** [comment]
npm seems a bit overkill for one package. Lets stay in the small/fast confines and not blow this project up too much. I tend to regret ever trying Javascript.

**Comment by zepatrik** [comment]
Well I agree that it would add a bit of overhead but on the other hand managing dependencies by hand is way more overhead. As with #189 there are two dependencies, this issue might add some too. `node_modules` tend to be the largest objects in the universe but that's nothing you have to handle manually.

**Comment by kordianbruck** [comment]
@zepatrik yea, that can be reduced to one. We can use NPM for that single javascript, but I would rather not setup a full build pipeline with webpack for that. This is a primary PHP application with all dependencies managed by composer and has a templating engine there. I see not reason to add any more complexity.

**Comment by zepatrik** [comment]
Ok, so I will add all dependencies manually.

**Comment by kordianbruck** [comment]
@zepatrik moment also has a composer package: https://packagist.org/packages/moment/moment

**Comment by zepatrik** [comment]
I have no idea how composer works but will have a look later.

**Comment by kordianbruck** [comment]
@zepatrik any update?

**Comment by zepatrik** [comment]
I'm not sure if it is the best idea to include all this javascript stuff over your build chain. I will probably start this project after the exams and do it independently via github pages. We can then add a redirect from tum.sexy
I will post an update here in march.

**Comment by kordianbruck** [comment]
Cool, I'll close the issue till then.
