### ISSUE TITLE
ma-sp.tum.sexy needs updated link to curriculum

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [mammuth/TUM.sexy#198]
I found that this link at the **Special area of sexy page** [ma-sp.tum.sexy](https://www.in.tum.de/fuer-studierende/master-studiengaenge/informatik/studienplan/fpo-2007-und-fpsos-seit-2012.html) is down.

**Comment by mammuth** [comment]
Thanks. Feel free to update the redirect! :blush:
It should link to the master informatics curriculum.

**Comment by cakebytheoceanLuo** [comment]
Yes. 
And other question, which must be asked before.  
Why do we not provide the other master major's curriculum, like `DEA`  at the page?

**Comment by mammuth** [comment]
Probably simply because none of the contributors was interested in it so far :wink:

**Comment by cakebytheoceanLuo** [comment]
Yes. I did the link update, which relates with this issue.   
Can we have a more detailed **guide** for the people like me, who want to contribute to this sexy page.  
The guide can this direction: How can we test the forked project locally at our PC?

**Comment by kordianbruck** [comment]
done.
