### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Alwinius** [mammuth/TUM.sexy#202]
The SSL Certificate of tum.sexy seems to have expired yesterday.

**Comment by kordianbruck** [comment]
Thanks for the heads up. I've renewed the certificate yesterday. Its a bit more complicated, as there are multiple parties involved in the renewal process and DNS changes seem to take longer than expected. I will have to investigate possibilities further in the future, on how to make acme.sh allow for longer cooldown during renewal.
