### ISSUE TITLE
hunger fetches wrong menu for FMI Bistro

### ISSUE THREAD

**Issue by maxOS1104** [mammuth/TUM.sexy#204]
hunger does not fetch / display the current menu for the FMI Bistro. It always shows the menu for the last week. For example, at the moment it displays [this menu](
https://intranet.in.tum.de/file/19n3b6k1j97ez/Fakultaetenwegweiser/-/FMI-Bistro-Speiseplan/Garching_Speiseplan_KW-03-2019.pdf) while the correct one would be [this one](
https://intranet.in.tum.de/file/16torzbkxwvra/Fakultaetenwegweiser/-/FMI-Bistro-Speiseplan/Garching_Speiseplan_KW-04-2019.pdf)

**Comment by mammuth** [comment]
Seems to be an upstream issue (https://github.com/srehwald/eat-api)

**Comment by jpbernius** [comment]
Fixed in upstream api.
