### ISSUE TITLE
Sexy Pretschi Game Link Dead

### ISSUE THREAD

**Issue by Hustenbonbon** [mammuth/TUM.sexy#206]
the link to the sexy pretschi game is dead. Do you know the authors? I could arrange infrastructure for it to run if that is the problem

**Comment by kordianbruck** [comment]
@Hustenbonbon yea, I'm the author. I thought everyone has forgotten about it by now. I might be able to find something in my archives. We can host it on tum.sexy no worries. 

Not sure if Prof. Pretschner appreciates it tho.
