### ISSUE TITLE
Solutions and Tests for past exams in EIDI2

### ISSUE THREAD

**Issue by nielstron** [mammuth/TUM.sexy#208]
I don't know whether this is the right place for it, but nevertheless.
A few friends of mine and me sat together and created solution proposals and tests for the OCaml part of older EIDI2/FuPV exams.
It could be placed on the website as old exams are (or where at least this year) published on the corresponding Moodle course. Thus students can check whether their implementations work and use the prepared angabe.
The link is https://github.com/nielstron/fupv_altklausuren

I'm posting this as an issue first because I wanted to get some feedback about whether this is the right place for the link. If so, I can surely create a PR for this.

**Comment by mammuth** [comment]
Well, we have nothing the like for other lectures yet. Basically the whole use case is covered by studystuff. If we'd start putting in exercises, summaries and stuff like that we'd start building a second studystuff - it's questionable whether we'd like to do that^^

Opinions @kordianbruck?

**Comment by kordianbruck** [comment]
I mean we can surely add a short link for the collection but I don't think people will look on tum.sexy for solutions for EIDI2. So if you just would like to have a short link to your repo, go ahead.

**Comment by nielstron** [comment]
>  Basically the whole use case is covered by studystuff.

I think this is right after all. Thanks for the feedback though!
