### ISSUE TITLE
Change the mailserver

### ISSUE THREAD

**Issue by kordianbruck** [mammuth/TUM.sexy#21]
http://mxtoolbox.com/domain/tum.sexy/

The mailserver from namecheap sucks. Compared to [this](http://mxtoolbox.com/domain/wdkk.de/)

Can we change it @krenzland?

**Comment by krenzland** [comment]
I honestly don't care that much, I had great experiences with Zoho Mail, but considering I'm only using the tum.sexy mails as a redirect... shouldn't matter.

**Comment by kordianbruck** [comment]
Set the MX record to server1.wdkk.de and tell me the redirects you want. I will set it up on my server then.

**Comment by kordianbruck** [comment]
Yep, no change.
