### ISSUE TITLE
FMI Bistro 404

### ISSUE THREAD

**Issue by Aevyz** [mammuth/TUM.sexy#227]
https://hunger.tum.sexy/

FMI Bistro link is not working, as the page that it links to 404's. More accurately, the website from the bistro is not working sensibly... https://www.wilhelm-gastronomie.de/ Currently KW 33-36 are all linking to the same PDF which is denoted by KW31 and is also not accurate for this week...

Just thought this should be known

**Comment by jpbernius** [comment]
Can you try to provide a fix here: [srehwald/eat-api](https://github.com/srehwald/eat-api)
It might be enough to change the url [here](https://github.com/srehwald/eat-api/blob/master/src/menu_parser.py#L178).

**Comment by jpbernius** [comment]
➡️ srehwald/eat-api#52

**Comment by jpbernius** [comment]
Fixed in upstream repository.
