### ISSUE TITLE
Restructure front page

### ISSUE THREAD

**Issue by kordianbruck** [mammuth/TUM.sexy#24]
As we get more items on the front page I would like to suggest  the following:
- Switch Projects / Links with About
- Tabbed Semesters: use tabs to only show one semester at a time

**Comment by mammuth** [comment]
I think it's good to have the about section slightly promoted, so people see they can add/update redirects themselves.

Tabs :thumbsup:

**Comment by jpbernius** [comment]
Cookie for storing selected tab?

**Comment by kordianbruck** [comment]
@jpbernius yes!

**Comment by kordianbruck** [comment]
![ec6ab69265ff4ff99b1f84093783bc97](https://cloud.githubusercontent.com/assets/298860/24683810/c2f6d8f6-19a1-11e7-87f3-6006abe0168e.png)

After tinkering with tabs, I came to the conclusion that those won't work. Heres my new suggestion instead - comments?

**Comment by mammuth** [comment]
:+1:

**Comment by kordianbruck** [comment]
Already done.
