### ISSUE TITLE
[HUNGER] No price shown for some Meals

### ISSUE THREAD

**Issue by jpbernius** [mammuth/TUM.sexy#25]
For Monday, there is no Price for the Käsespätzle.
![screen shot 2015-11-09 at 10 59 58](https://cloud.githubusercontent.com/assets/6382716/11030894/36f2248c-86d1-11e5-95d1-4a219e2908a0.png)

Line in PDF is:

```
1.V Käsespätzle mit Röstzwiebeln 1,9,15,16 2.95
```

[KW46_Speiseplan_IPP_vom_9.11.15_bis_13.11.15.pdf](http://www.betriebsrestaurant-gmbh.de/uploads/media/KW46_Speiseplan_IPP_vom_9.11.15_bis_13.11.15.pdf)

so the 'Zusatzstoffe' are just before the Price. There needs to be a special case in the Parsing code.

**Comment by mammuth** [comment]
Thanks.
Might you try to figure out why the regex is failing in this case and fix
it in a pull request?

**Comment by kordianbruck** [comment]
@mammuth the regex is not build for dual numbers. \d only grabs on to a single digit, not a number. I'll fix something up maybe. (Also we should do this in one regex, as each execution takes up more time...)

**Comment by jpbernius** [comment]
are there any objections on introducing a template engine?

**Comment by kordianbruck** [comment]
@jpbernius what kind of template engine do you have in mind? 

@mammuth /[1-9][0-9]*(,[1-9][0-9]*)+/ works for my tests (Tried it out on http://regexpal.com/), but I don't know why you have strings in the current regex. Can you maybe explain your thought process, as the code is not very well  documented :+1:

**Comment by jpbernius** [comment]
idk. Handlebars possibly. Currently it is very ugly.

**Comment by mammuth** [comment]
@kordianbruck 
`$meal = preg_replace('/ oder B.n.W. /', '', $meal);`
`// Remove Zusatzstoffe numbers`
`$meal = preg_replace('/((\d,\s*)+\d)/', '', $meal); // abc 1,2,3 xyz`
`$meal = preg_replace('/(\s\d\s)/', '', $meal); // abc 1 xyz`

The whole intention has been to remove those Zusatzstoff notices. They could be merged into one regex. The \s* is because sometimes the PDF contains whitespaces between the listing of the Zusatzstoffe (like 1, 2,3) :unamused:

The first row is for removing the *oder B.n.W*. This should be transformed into a normal string replacement.

It looks like your suggested regex doesn't match *1, 2,3* and *1*, right?

**Comment by kordianbruck** [comment]
@jpbernius twig is now used for templating. Now do the regex  :yum: 

@mammuth this is annoying. Yes you are right, mine does not catch that case.

**Comment by jpbernius** [comment]
Ok, so I digged into the Problem. And apparently there is an error in the PDF (it says 2,95 instead of 2.95)

I guess there is no point in fixing that.
However I improved the regex and a single regex statement.

**Comment by mammuth** [comment]
Yep, their PDF's could be the definition of inconsistency...

**Comment by kordianbruck** [comment]
![screenshot from 2015-12-04 10-42-18](https://cloud.githubusercontent.com/assets/298860/11595183/c9f74de2-9a73-11e5-9ce3-efadc426919a.png)

Not working too great...

**Comment by jpbernius** [comment]
![screenshot-2015-12-14](https://cloud.githubusercontent.com/assets/6382716/11781055/331d28be-a267-11e5-89ba-65855e2b71b5.png)
Working great for this week.

**Comment by mammuth** [comment]
Do you have a fix for last week?

**Comment by jpbernius** [comment]
Not yet. This is possibly due to inconsistent Currency format.
I'll try to match for the Euro Sign. Maybe that works.
