### ISSUE TITLE
Docker PHP:7.3 != Travis PHP:7.2

### ISSUE THREAD

**Issue by cs8898** [mammuth/TUM.sexy#263]
Travis uses PHP7.2 to deploy PHP7.3 Container

Should be switched to PHP7.3 in Travis File
Or the Docker file should be based on the current PHP version

I will try that later, how i can tell the Dockerfile what PHP version it should use...

**Comment by kordianbruck** [comment]
I guess you mean this line?
https://github.com/mammuth/TUM.sexy/blob/master/.travis.yml#L38
Why would this really matter? The differences between 7.2 and 7.3 are minimal.

**Comment by cs8898** [comment]
As you said the DIFFERENCES, its just like saying i will use windows7 for my system test because windows is windows... While i'm actually targeting windows10...

Its just not correct

**Comment by mammuth** [comment]
> Its just not correct

I would agree, generally. But in this case, the PHP version in the mentioned line isn't even relevant for anything, is it? The docker image just pins 7.3.

I'm not sure how the deploy part of Travis works - is this line telling Travis to somehow use artifacts of the php7.2 job? Or why would it be needed otherwise? 

Anyway, feel free to "fix" this if you'd like to.

**Comment by jpbernius** [comment]
Hi, I did set this up originally so I can give a few insides here.

> its just like saying i will use windows7 for my system test because windows is windows... While i'm actually targeting windows10...

This is not the case here, as no php is executed in the deployment. We need to specify one version here, as we only want to deploy once.
As @mammuth pointed out, the version that is actually deployed is defined in the docker file.

However, feel free to upgrade the last line in the `.travis.yml` file, as this will make it less confusing. Maybe add a comment with the reasoning behind this, so we have or documented in place.
