### ISSUE TITLE
Integrate mensa people count

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#265]
As discussed in the mensa counter repo: https://github.com/dieliste/mensa/issues/4

View to embed: https://mensa.liste.party/minimal/

Example:
![69812509-8f2aee00-11f0-11ea-80f3-5786f3697d5f](https://user-images.githubusercontent.com/3121306/69946739-8a19b780-14ec-11ea-8403-858386d0aa59.png)

**Comment by mammuth** [comment]
Done in

**Comment by kordianbruck** [comment]
in ????

**Comment by mammuth** [comment]
Well. Somewhere. Via GitHub editor... :see_no_evil:
