### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by simonbohnen** [mammuth/TUM.sexy#294]
There is something wrong with the SSL certificate of tum.sexy:
<img width="741" alt="Screenshot 2020-08-21 at 11 13 35" src="https://user-images.githubusercontent.com/26229617/90874025-5bf04680-e39f-11ea-9feb-c428303badc4.png">

**Comment by mammuth** [comment]
@simonbohnen can you provide information about the certificate that you're getting? I'm connecting with a valid certificate by Let's Encrypt.

**Comment by kordianbruck** [comment]
I don't see any issues here. More infromation is required, e.g. what URL you are visiting and the cert details please.

**Comment by simonbohnen** [comment]
The URL is https://tum.sexy. I'm using Chrome version 85.0.4183.83 on macOS Big Sur Beta 5. I'm getting the following nondescriptive error for the certificate:
<img width="489" alt="Screenshot 2020-08-26 at 19 46 40" src="https://user-images.githubusercontent.com/26229617/91338199-dde3d380-e7d4-11ea-9c1d-ce9ceceec4e6.png">

I'm also unable to reproduce this on any other browser / operating system / device. Looks like it's not too relevant now, I will post again if this persists in the release of macOS Big Sur.

**Comment by simonbohnen** [comment]
This is the zipped cert I'm getting:
[tum.sexy.cer.zip](https://github.com/mammuth/TUM.sexy/files/5131449/tum.sexy.cer.zip)
