### ISSUE TITLE
Hunger: "mit B.n.W." -> "natürlich mit Wedges!11!!"

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#31]
Replace "mit B.n.W." with "natürlich mit Wedges!11!!" 

Epic feature.

**Comment by krenzland** [comment]
Closed due to lack of wedges.

**Comment by mammuth** [comment]
Sad but true.

**Comment by kordianbruck** [comment]
So sad

![image-1105584-860_poster_16x9-qiqk-1105584](https://user-images.githubusercontent.com/298860/28898152-a45e6156-77e4-11e7-85b6-57c7d7292905.jpg)
