### ISSUE TITLE
Hunger is showing the wrong Day

### ISSUE THREAD

**Issue by ldoench** [mammuth/TUM.sexy#32]
It shows the next day not the current day

**Comment by mammuth** [comment]
This happened before, if the Speiseplan-PDF doesn't contain a section for every week day.
However this week there are all 5 days in the PDF.

@kordianbruck you added a hotfix for that directly on your server, some time ago. Did you revert it? Otherwise that might cause this problem now?

**Comment by kordianbruck** [comment]
Updates usually overwrite any hotfixes. So probably this is gone by now.

The only option I see is to have passed days shown via a dropdown or show/hide mechanic

**Comment by mammuth** [comment]
Nah, I don't think we need drop downs, we should rather handle the days properly. 

Currently the chosing of a day is done based on the number of the day in the PDF. As a result it gets messed up, when the PDF doesn't contain all 5 days, but only 4, if the Monday is a holiday for example. 

It should be possible to match the correct day based on the name in the PDF "Montag, 5. Februar"
