### ISSUE TITLE
Provide parser for openmensa.org

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#35]
https://openmensa.org/contribute

**Comment by kordianbruck** [comment]
Meh, ruby.

**Comment by mammuth** [comment]
There are wrappers for eg. Python: https://github.com/mswart/pyopenmensa

**Comment by krenzland** [comment]
We only have to create an XML-File ([feed format](http://doc.openmensa.org/feed/v2/)), there's no need to use Python/Ruby.

**Comment by kordianbruck** [comment]
Really depends on #67 right now
