### ISSUE TITLE
Safe Browsing Error on Chrome

### ISSUE THREAD

**Issue by hbirler** [mammuth/TUM.sexy#43]
"Google Safe Browsing recently detected malware on tedx.tum.sexy. Websites that are normally safe are sometimes infected with malware. "
https://www.google.com/transparencyreport/safebrowsing/diagnostic/index.html?hl=en-US#url=http://tedx.tum.sexy/

**Comment by mammuth** [comment]
Interesting, I have no Idea why tedx.tum.sexy is flagged, while tedxtum.com isn't. We're just doing a redirect with via a raw header.
@kordianbruck any idea what's causing this?

**Comment by kordianbruck** [comment]
Maybe it thinks, that we are trying to imitate tedx - dunno really, there isn't any simple way I know of to check why we got blocked.
