### ISSUE TITLE
Add Analytics 

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#45]
Add Google Analytics / Piwik so we know how many people use which parts of the site

- Redirects
- Frontpage
- Hunger
- Rooms

**Comment by kordianbruck** [comment]
Why not use a simple counter in the apc cache for each endpoint? Do we really need a large framework like piwik?

Using the cache, we can even sort the links according to popularity.

**Comment by mammuth** [comment]
Your second point makes sense.

GA / Piwik is easy to add and gives more information than just a plain counter, I don't see why we shouldn't add GA / Piwik.

**Comment by kordianbruck** [comment]
I'd rather add Piwik than GA, but in any case, I don't think spying on our users is needed. A simple hit counter would be sufficient as well.

**Comment by mammuth** [comment]
I don't see using anonymized Piwik (with 2 bytes erased from the IP) as
"spying on users".

**Comment by zepatrik** [comment]
I agree with @kordianbruck that it isn't nice to inform google or any other provider about every user if just a simple counter is needed. Users really concerned about privacy of course block GA/... and that will result in incorrect stats. I have no clue how many people use tum.sexy but I think you will get quite inaccurate numbers when only a few block GA

**Comment by kordianbruck** [comment]
@mammuth I'm setting up my docker infra right now. Might be able to finally setup that piwik instance then :dancer:

**Comment by kordianbruck** [comment]
Right now we have a log analyzer for the time being. Its sufficient I think - @mammuth ?

**Comment by mammuth** [comment]
It is in my opinion! Let's close this.
