### ISSUE TITLE
Hunger: kcal information destroys parser

### ISSUE THREAD

**Issue by krenzland** [mammuth/TUM.sexy#49]
The FMI bistro pdf now includes the amount of calories for each meal.

Whilst that might be healthy, it completely destroys the mighty regex and thus also the result.

**Comment by kordianbruck** [comment]
PDFs are here: http://www.betriebsrestaurant-gmbh.de/index.php?id=91

**Comment by mammuth** [comment]
Btw, the link is no deep link to the affected PDF I'm afraid.

I think the affected PDF was the one in KW4?
The filename of KW06 is _./KW06_Speiseplan_FMI_vom_6.2.17_bis_10.2.17.pdf_ (located at http://www.betriebsrestaurant-gmbh.de/uploads/media/KW06_Speiseplan_FMI_vom_6.2.17_bis_10.2.17.pdf), so one might think KW4 is located at _./KW04_Speiseplan_FMI_vom_23.1.17_bis_27.1.17.pdf_, but hey, it wasn't the FMI Bistro, if they'd obey their own patterns. 😁

**Comment by mammuth** [comment]
Ah, and in KW6, there seem to be no clue about the calories.

**Comment by mathiasquintero** [comment]
I thought this was already fixed

**Comment by mammuth** [comment]
Well the PDF's are really inconsistent and from time to time there occur new bugs / issues with the parsing...
