### ISSUE TITLE
tum.sexy/rooms redirects to https

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#51]
http://tum.sexy/rooms/ redirects to https://tum.sexy/rooms/ which fails

**Comment by kordianbruck** [comment]
We are getting the data from: https://campus.tum.de/tumonline/wbrisweb.status_mobile_mi

That page now redirects to the new official web app. We should consider also redirecting to the offical app instead of doing our own thing. 

Offical URL: https://www.devapp.it.tum.de/iris/app/

**Comment by mammuth** [comment]
Yes, we should probably just redirect to the new official App.
