### ISSUE TITLE
Hunger: Support New Bistro Owner

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#67]
Apparently the new owner started providing PDF menus, as seen at the MPI page: https://mpi.fs.tum.de/neu-an-der-tum/am-campus/essen-trinken/

The owner's page currently does not provide a link to the bistro PDF. 

So assuming we can automatically retrieve the PDF in the future (which is a high probability), we have two choices:
- Writing another buggy PDF parser
- Displaying the PDF as an image on the page

I think I'd be fine with option 2 (at least as a short term solution). A problem is the landscape format of the PDF which probably sucks on mobile devices since you need to zoom and scroll horizontally...

**Comment by ldoench** [comment]
You could only display the current (and maybe the next day) of the pdf and then it could be readable on mobile devices as well.

**Comment by mammuth** [comment]
Yes, cropping the PDF/Image might be an easy solution. Although it's not machine readable then.

And it also highly depends on the consistency of the PDFs.

**Comment by pfent** [comment]
I played around a little bit over on my [FMIBistroParser](https://github.com/pfent/FMIBistroParser) repo. (It's C++ tough)

I used the thought to only display the current "column" to split the PDF's text vertically for each day. The current PDF then translates to this text (SeemsGood?):
```
Kohlrabi Cremesuppe
Allergene: Sellerie, Milch
€ 1,00
Farfalle mit Käsesauce, Rucola und Cocktailtomaten
Allergene: Milch, Gluten
€ 4,30
Zwiebelfleisch aus dem Ofen mit Bratkartoffeln
Allergene: Sellerie
€ 5,30
**********************************************************************
Kresse Suppe
Allergene: Sellerie, Milch
€ 1,00
Gemüsecurry mit Basmatireis und Koriander
Allergene: Sellerie, Milch, Soja
€ 4,30
Wammerl kross und Kartoffelsalat
Allergene: Sellerie
€ 4,90
**********************************************************************
Kartoffelsuppe mit Gemüsestreifen und Majoran
Allergene: Sellerie
€ 1,00
Vegetarische Lasagne mit Tofu
Allergene: Sellerie, Milch, Gluten, Ei
€ 4,30
Lammcurry mit Reis
Allergene: Sellerie, Milch
€ 5,30
**********************************************************************
Gemüsesuppe mit Eierstich
Allergene: Sellerie, Ei
€ 1,00
Kartoffelknödel-Auflauf mit Spinat
Allergene: Sellerie, Gluten, Milch
€ 4,30
Münchner Tellerfleisch, Wurzelsud, Kartoffeln dazu Kren
Allergene: Sellerie, Milch
€ 5,30
**********************************************************************
Maiscremesuppe mit Lauch
Allergene: Sellerie, Gluten, Milch
€ 1,00
Pasta mit gebratenem Gemüse und Parmesan
Allergene: Milch, Gluten, Sellerie
€ 4,30
Nürnberger mit Sauerkraut und Kartoffelpüree
Allergene : Sellerie, Milch
€ 4,90
**********************************************************************
```

**Comment by mammuth** [comment]
Cool @pfent! Yeah, the results actually look pretty good! 🎉 

> I used the thought to only display the current "column" to split the PDF's text vertically for each day. 

How do you determine which column to display for the current day?

**Comment by pfent** [comment]
Since libpoppler aligns the document with spaces, I separate the days by the first character column for each day of the week.
E.g. "Dienstag" starts at character 42, and "Mittwoch" at 90, so in the consecutive lines, everything between character 42 and 90 should be for "Dienstag" :)
The I remove all the superfluous whitespace, put the description and allergens in one line and print everything

The approach works fine for this PDF, if you have more test samples, I'd love to test if the approach works for the other PDFs

**Comment by mammuth** [comment]
Alright. 
So probably a simple check whether the column which you expect to be the "Dienstag"-column contains "Dienstag" (and not "Mittwoch" in case Tuesday is holiday) would be sufficient to assume that the column is correct.

What if they change the layout a bit and there is eg. more whitespace before the table starts or each table is a couple of characters wider? 

> The approach works fine for this PDF, if you have more test samples, I'd love to test if the approach works for the other PDFs.

Sadly I don't have any more samples yet. We probably need to wait for the next week (and maybe ask someone at the  student council where they got the first PDF from).

Btw, the website where I assume the PDF's will be published in the future is: http://www.wilhelm-gastronomie.de/uni-gastronomie

**Comment by pfent** [comment]
Nah, currently I just expect them to leave the column empty when the day's a holiday...
[My day detecting regex](https://github.com/pfent/FMIBistroParser/blob/master/main.cpp#L90) just detects on which character column the first character of the (hardcoded) days starts
I guess we can see what they'll do on 2017-08-15

> Btw, the website where I assume the PDF's will be published in the future is: http://www.wilhelm-gastronomie.de/uni-gastronomie

I currently scrape the FSMPI website for the URL, let's see who has more consistent naming...

**Comment by kordianbruck** [comment]
Any ideas on how to actually run this in the PHP environment on the server? :dancer:

**Comment by pfent** [comment]
@kordianbruck what about `shell_exec`?
I can provide you with a binary, so you don't have to install cmake/gcc or boost on the server. However curl and poppler still need to be linked in and installed.

**Comment by kordianbruck** [comment]
Can you setup a microservice somewhere? :men_wrestling: 

Nah, alright, we can try that for sure. Are you willing to write that integration?

**Comment by pfent** [comment]
I have no clue about that PHP stuff 🤷‍

However, I set up a "microservice" (*cough* cronjob), reachable under:
http://home.in.tum.de/~fent/getCurrentSchedule

**Comment by Gambleon** [comment]
The url is http://www.wilhelm-gastronomie.de/tum-fmi-bistro

**Comment by Gambleon** [comment]
Full url http://www.wilhelm-gastronomie.de/wp-content/uploads/2017/09/Garching-Speiseplan_KW39_2017.pdf

(Sorry, can't edit on mobile)

**Comment by srehwald** [comment]
You might also want to consider the API I was recently working on: https://github.com/srehwald/eat-api
It generates static JSON-files that are accessible via Github Pages. Just call
`https://srehwald.github.io/eat-api/<location>/<year>/<week-number>.json` and you will get the menu for a specific week at a specific location. So far, Mensa {Garching, Arcisstraße, Großhadern} and the FMI Bistro are supported.
