### ISSUE TITLE
Automatic redirects using htaccess and script

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#7]
Idea:
- make a redirectRules.json file containing all redirects with fields: subdomain, target-url, description
- read this file from the main page to display a list of all avaiable redirects
- read this file (once on git pull?) by ./redirects.php to know the redirection rules
- htaccess which maps xy.tum.sexy -> tum.sexy/redirects.php?sub=xy

Pro:
- redirectRules.json is easy to update (by anyone using pullrequests)
- automated 
- possibility to add simple tracking features to determine which subdomains are most famous/used

Contra:
- performance?

Dupe of #3, work in progress by @prexlebre , let's see which solution is _better_ (or can be used earlier - you're....4 month(?) ahead, so we've got some time to relax with this solution :stuck_out_tongue_winking_eye: )

**Comment by kordianbruck** [comment]
Performance is not an issue. The same thing is done by namecheap, only on their servers. The is no real 'DNS redirect', only HTTP Headers can instruct browsers to go to another location.

Put the rules in a 'routes.php' file, so we make use of the php caching mechanics.

**Comment by mammuth** [comment]
Automatically display a list of redirects on the mainpage is done in commit 4381f57
