### ISSUE TITLE
Error 500 when using redirect functions

### ISSUE THREAD

**Issue by Masrepus** [mammuth/TUM.sexy#77]
When trying to call any [shortcut].tum.sexy site, an error 500 is returned

**Comment by mammuth** [comment]
Jup, your commit I merged had a syntax error in it 😜

**Comment by Masrepus** [comment]
Haha man, a comma as always 😂
Thanks, didn't see that

**Comment by kordianbruck** [comment]
I'd lol if it wouldn't be that sad :sob: 

jkjk, nice one!
