### ISSUE TITLE
Add category for electives to page

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#78]
We currently only display lectures for Bachelor's semesters 1-6 and a "special" category. We should probably add a category for all those electives that don't appear on the page right now.

**Comment by kordianbruck** [comment]
This will get messy really fast. Can we integrate a search?

**Comment by mammuth** [comment]
This will be messy! But it's better than hiding the information in my opinion. 
Adding a search is a cool idea 👍 
But I think we can get the electives category in and add the search later on.
