### ISSUE TITLE
Subsubdomain redirects are not working 

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#9]
For the case we want to add subsubdomains like pizza.hunger.tum.sexy

**Comment by kordianbruck** [comment]
I don't think that will work at all. You would need a DNS server for hunger.tum.sexy which knows the ip for pizza.hunger.tum.sexy - this is really overkill. You might want to reconsider something like pizza-hunger.tum.sexy

**Comment by mammuth** [comment]
Correct. I just filed the issue for completeness, *for the case we want to add subsubdomains*

Is there an actual need for subsubdomains at all?

**Comment by kordianbruck** [comment]
No.
