### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by lukaskollmer** [mammuth/TUM.sexy#91]
The main page is broken, as are all redirects

![image](https://user-images.githubusercontent.com/6547384/32828444-662a7ed0-c9ef-11e7-9d64-df1c88a42e94.png)

**Comment by kordianbruck** [comment]
@lukaskollmer thanks for noticing and reporting. 

The hoster had a downtime and somehow didn't properly resume the VM. Reboot helped.
