### ISSUE TITLE
hunger.tum.sexy: Show monday on saturday and sunday

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#99]
If the speiseplan of the upcoming week is already available, we should display the dishes of monday on the weekend before.

cc @jpbernius

**Comment by jpbernius** [comment]
The [fmeat.php Library](https://github.com/jpbernius/fmeat.php) now provides this additional API with Version 1.2:
```php
getNextWeekForLocation(string $location): Week
```
